
// http://engl393-dnd5th.wikia.com/wiki/Backgrounds
#[derive(Clone, Copy, PartialEq)]
pub enum Background {
    Acolyte,
    Anthropologist,
    Archaeologist,
    BlackFistDoubleAgent,
    CaravanSpecialist,
    Charlatan,
    CityWatch,
    ClanCrafter,
    CloisteredScholar,
    CormanthorRefugee,
    Courtier,
    Criminal,
    Dissenter,
    DragonCasualty,
    EarthspurMiner,
    Entertainer,
    FactionAgent,
    FarTraveler,
    FolkHero,
    GateUrchin,
    Gladiator,
    GuildArtisan,
    GuildMerchant, // Variant of GuildArtisan
    Harborfolk,
    HauntedOne,
    Heretic,
    Hermit,
    HillsfarMerchant,
    HillsfarSmuggler,
    Inheritor,
    Initiate,
    Inquisitor, // Variant of CityWatch
    Investigator,
    IronRouteBandit,
    Knight, // Variant of Noble
    KnightOfTheOrder,
    MercenaryVeteran,
    MulmasterAristocrat,
    Noble,
    Outlander,
    PhlanInsurgent,
    PhlanRefugee,
    Sailor,
    Sage,
    SecretIdentity,
    ShadeFanatic,
    Soldier,
    Spy, // Variant of Courtier
    StojanowPrisoner,
    TicklebellyNomad,
    TradeSheriff,
    UrbanBountyHunter,
    Urchin,
    UthgardtTribeMember,
    Vizier,
    WaterdhavianNoble
}
